
CREATE TABLE Ta(
	aid INT NOT NULL, 
	CONSTRAINT PK_Ta PRIMARY KEY (aid),
	a2 INT UNIQUE
);

CREATE TABLE Tb(
	bid INT NOT NULL, 
	CONSTRAINT PK_Tb PRIMARY KEY (bid),
	b2 INT 
);

CREATE TABLE Tc(
	cid INT NOT NULL, 
	CONSTRAINT PK_Tc PRIMARY KEY (cid), 
	aid INT REFERENCES Ta(aid), 
	bid INT REFERENCES Tb(bid)
	);

